### ISSUE TITLE
How does the polling work?

### ISSUE THREAD

**Issue by JesseB0rn** [Tommrodrigues/homebridge-http-garage#1]
Sorry for the stupid question. But, I could not quite figure this out. For the Statepolling, does the server simply respond with 1 or 0 rather than text/HTML?

**Comment by phenotypic** [comment]
By default, state polling is disabled. You can enable it in the `config.json` though by setting `polling` to `true`

If you do this, your device will be polled every `120` seconds (by default). When polled, your device should return return HTML `200` with just a `1` or `0` depending on the state. 

If you want to see an example, please look in the `examples` folder at the `NodeMCU-Garage.ino` between lines `93` and `113`
