### ISSUE TITLE
New property to identify the status of the door

### ISSUE THREAD

**Issue by jmaferreira** [Tommrodrigues/homebridge-http-garage#4]
Hi,

I'm using this plugin to control a Shelly 1 on my garage door. It works great except that the Shelly API does not return the status as a simple 0 or 1. I need to transform the response before feeding it to the plugin which is not very practical.

Shelly's response is as follows:

```json
{
"ison": false,
"has_timer": false,
"timer_started": 0,
"timer_duration": 0,
"timer_remaining": 0,
"source": "timer"
}
```

The importante property is `ison` obviously.

What I want to do is to be able to instruct the plugin where to look for the status by means of its configs. I'm willing to do the coding work, will you merge it afterwards?

Any suggestions on how the configs should look like?

**Comment by jmaferreira** [comment]
This plugin does something of the sort response mapping but looks too complicated:
https://github.com/mach1009/homebridge-http-garagedoor#response-mapping

**Comment by phenotypic** [comment]
Hi there, this should be an easy fix. All you need to do is fork the plugin and replace instances of `json.currentState`.

If `false` signifies open, replace `json.currentState` with `json.ison`, if `false` signifies closed, replace it with `!json.ison`.
